version: '3.3'
services:
    nginx:
        image: nginx:1.13
        volumes:
            - ./news_provider:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "8000:80"
        depends_on:
            - php
    php:
        build:
            context: ./php
        volumes:
            - ./news_provider:/var/www/html
        ports:
            - "9000:9000"
        depends_on:
            - db
        env_file:
            - ./params.env
    news_crawler:
        build: ./news_crawler
        depends_on:
            - db
        env_file:
            - ./params.env
    db:
        image: mysql:5.7
        ports:
            - "3307:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./mysql:/docker-entrypoint-initdb.d
        env_file:
            - ./params.env
        command: --innodb-use-native-aio=0