CREATE TABLE IF NOT EXISTS `noticias` (
  `ID` varchar(500) NOT NULL,
  `FONTE` varchar(100) NOT NULL,
  `EDITORIA` varchar(150) NOT NULL,
  `TITULO` varchar(250) NOT NULL,
  `DATA_ATUALIZACAO` date NOT NULL,
  `HORA_ATUALIZACAO` time NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `noticias`
  ADD PRIMARY KEY (`ID`);
COMMIT;
